travis:
  secure:
    BINSTAR_TOKEN: KkLVQE/Bla7anQx+XCY3EL9xtWmXz7rOZr5pxFC4LAU+nTTlSigMKwg+MlZppbzSdGPnTiVBQsbP/vvmkiLD06BDzt1BiAyscXdLjqadzP9D/nOGf1VDCoAW0D/LTw76kZxkbXiyhsk96yqA6iFDy9VWGwS4T/ST6UJXwbq72LS1NJEAVcp2oZ4MwBqenL2NDzTH8gilck+W1DeNmaLc35JO5iSSnrQTdg5iz/GCC4g1EKu0ssp/KFuVa2zAmMjbh/qnZvEAVTB5bLjgVKB0Hx/A/4/pDnvlZnfZdhY4iHOFuQlgcYIi+yONrPSuUpgcoqieyUdicakHr8ggXPLEQnWPWjJrvWpekorl7PBigcg0XVBbaB0/QpyPpKstKaRZDAMdbA89bT7xKO/r15ZBCYJqwPPHT5dzEr1kpflE/WRXoKhXJV7yWyx8EoQ8gRANZX4nFUfvSt4HnT2i38a9O3rHogqesTa0mc2tBrPVs3jf0utoT5xSCeGA6gX999upsYVSjoJHcDtScQOsnB5DBCOTl/yDpcaEwJj1RawFNJa/v7/GKQpkpzFZ3C8gNHBpInBDZaDU56aVtlCEpIM7xxQvI+aMCP69Zp3c8eZDHhHkZ0CZkeLu5P1V4ZMy5thSU6pOiM+muMP4IF+qqtgCPKPGa+02DLDGUnhqNxi2WbM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
