travis:
  secure:
    BINSTAR_TOKEN: vA1soMiZ8S3Ny+tp4go7gfmc+lz0oYs0pv3YS46nyvvBeo60GpXeGWi7zOVJARnvtY3p10u0Kic6n58MMmzQqnU8aIRkUfoARUyh0ENifkHQhvnjkBB9oY+q/ZnFZK1Y5BVStRJQ2eHRDqMqovvujfHsazuRvbfo2sRnIX2mFFfFO9JVpuVpiPWz8A3P40q3J2tj5VebmS5tA97H6r3FRf4onwycri4yMq2YKcLl88yTQWZsw+4c/1/q92fSOrRNIeMU2cPmPP9rEzsL+1WZUhBw58OiyNWEPoKW4Oy374J2fXL4zhpid3TGV7ZH/fonpTaD3iH0SkkMsYLOGT7tkvZ21IkhHkba5wsTPV7F7JZeKUIMqkQUTt4yxd27eVFLx94abCXrVCbWmw4aVbrQDfS9ZgBPqK6Lymy5/xJFbnm43cep39vE405P83XUHP6eHXD1ax+WXzpFIqnX9sxyenQ08LfllXeHdBMhfr8/vP2aerUz1iN2smCG3A+1VUIMA1FXYpmUtWFpip83y0Cx2j4FrjRml+ZCSEwMkl7NtIwMavQaxvf62A1t7e1lZNJo88VJNS0HTZe+p4mIZ7beC8B+UM5gt6Do1hWo6EbKJkS4wqEfTw7ZmI7LuUzB9KJJEGlVMYa4Iq+s+WhCqezgqJ68WqJLcLS+1f97CuUC1fw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
